### ISSUE TITLE
Dev Kickoff meeting

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1191]
Set up a dev kickoff meeting between GC Forms and GCDS. The main point of contact on GC Forms is Tim.

There is an existing slack channel [#ds-forms-integration](https://gcdigital.slack.com/archives/C07CKTG40F3), in which leads are informed of the collaboration and are aware of the capacity involved that is required from both teams.

**Comment by adorayi** [comment]
Please add expected outcomes and details to the ticket @daine

**Comment by daine** [comment]
Met with Tim today, and we discussed the following:
- They are trying out tokens and it seems like a good approach for now. Using our tokens is a good start since it doesn't have huge impacts on how their system functions and the impact is minimal and mostly for visual purposes. It is a straightforward path vs GCDS components where there are more battles to tackle.
- The current blockers to GCDS components so far are:
  - https://github.com/cds-snc/gcds-components/issues/652
  - https://github.com/cds-snc/gcds-components/issues/653
- There is still potential to try out a component like the Header or the Footer. We've recommended having a look at some of our simpler components like Heading and Date Modified.

We're keeping an open line through direct messages for now to keep the feedback loop open.
