### ISSUE TITLE
Website search: include global search box, to indicate integration 

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#209]
Global search: include global search box, to indicate integration

**Comment by ethanWallace** [comment]
Due to the design system and it's content being still in development, and the site content not being indexed to be included in the search, the global search will not be added to design.alpha.canada.ca.

To add the search at a later date with the `gcds-header` component, just add the search form into the children elements of the `<gcds-header>` and apply a `slot="search"` attribute to the search element.

**Comment by ClementineHahn** [comment]
@abdul-CDS Make 2 cards out of this : 
1) the mandatory compnent (UI)
2) Functionality + UI for ourselves (this one to evolve)

**Comment by abdul-CDS** [comment]
Done.

**Comment by ethanWallace** [comment]
## Integrating search into our documentation site

Two options

### 1. Global search

Using the page linked on https://design.canada.ca/common-design-patterns/search-box.html we integrate our content into the global search on canada.ca.

This requires submitting an online form to PP.

### 2. Site only search

Using a combination of 11ty serverless ondemand template builder and https://www.belter.io/eleventy-search/, we could build a search page. 11ty serverless allows us to create pages on demand so search result could be generated based on a query using Elasticlunr.

For this to work we would need to update the frontmatter for every component page to include extra details and make sure our page titles are unique(they could use some work).

**Comment by adorayi** [comment]
We will proceed with option 1, @adorayi and @ClementineHahn to follow up. Also check in @mcman12, @sarahpiovesana on the implications of including our DS site in the Global Canada.ca search.
Site only search will be put into the backlog to be prioritized.
