### ISSUE TITLE
EN Content: Breadcrumb component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#340]
**Summary:** Documentation of component guidance in EN for the Breadcrumb component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #403 #402 #154 #331

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by melaniebmn** [comment]
[Draft](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=9608-57381&t=aLjjk5s2j1k6NTF2-0) for breadcrumbs guidance.

**Comment by nchoquet** [comment]
test mention @nchoquet

**Comment by nchoquet** [comment]
Test mention @nchoquet

**Comment by ClementineHahn** [comment]
Still need for @SmartMouthWords with @melaniebmn to check off last boxes then Dylan before sending to translation

**Comment by ClementineHahn** [comment]
Still need for @SmartMouthWords with @melaniebmn to check off last boxes then Dylan before sending to translation

**Comment by ClementineHahn** [comment]
@nchoquet this is ready for translation :)  Link of material here https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=9608-57381&t=aLjjk5s2j1k6NTF2-0

And contacts are @melaniebmn and @SmartMouthWords

**Comment by SmartMouthWords** [comment]
Need to make some updates to the English before publishing based on a couple changes to terminology made after sending to translation

**Comment by SmartMouthWords** [comment]
Identified 7 possible additions from new [Canada.ca breadcrumbs guidance ](https://design.canada.ca/common-design-patterns/breadcrumb-trail.html). 

- [ ] Reviewing with @melaniebmn
- [ ] Will pull in French from Canada.ca as much as possible
- [ ] Send to Nicholas for missing French and review of French from Canada.ca DS
- [ ] Complete bilingual review

**Comment by SmartMouthWords** [comment]
**Changes based on Canada.ca guidance pivot:** 

- Use either "Home" or the name of the process or application as the text of the first breadcrumb link on transactional pages that use a breadcrumb trail.

- “Maintain the Canada.ca link as the default first breadcrumbs link for most websites and pages."
- "Opt to replace the Canada.ca link with the homepage link on transactional pages and stand alone websites or products. To remove the Canada.ca link at the head of the breadcrumbs, set the <hide-canada-link> to "false".” 

**Changes made to pull in some Canada.ca new guidance and reworked it so it fit in GC Design System:**  
- “Tip: For a process that does not have a traditional landing page, link to the starting page of the process.”   
- " When selected, each breadcrumb should bring the user to a unique page.: Avoid duplication by linking each breadcrumb to a unique page."  
"Shorten parent page link text to improve readability and reduce space. Where possible, reflect the title of the page in the breadcrumb without including the full page name."  
- Added chevron to the anatomy. 
- Added the total max number of links since the first one is now variable under the new rules. 
**Other changes**
- Updated this section in “Design” to be more slightly more content / less code focused: “Place breadcrumbs at the top of a page, before the main content. This way the skip-to-content button can work to let a person skip all navigation links, including breadcrumbs.” 
- Updated intro text for use cases for precision: Use breadcrumbs to signal a visitor’s current location  give them a sense of place in the  navigation model, and to:
- Changes some of the ordering and subtitles to put the most important info first and be clear about what’s in each subsection.

**Comment by SmartMouthWords** [comment]
@nchoquet The updated [breadcrumbs content ](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=10318%3A76595&mode=design&t=lRDI9EGK9yQsz1HQ-1)is ready for translation. Changes in pink.

**Comment by nchoquet** [comment]
@SmartMouthWords updated [FR content here](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=10418-76922&mode=design)

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete

> **EN**: https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=10318-76595&mode=design&t=36cOiS43f1Di7yS6-0 
> **FR**: https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=10418-76922&mode=design&t=3IZMNZHChuWMMrCZ-0

# 🚀 Ready for dev
> @ethanWallace @melaniebmn @dylanzheng94 @ClementineHahn
