### ISSUE TITLE
Component quick guide

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#397]

**Comment by ClementineHahn** [comment]
draft is therehttps://docs.google.com/document/d/1UjRNoAXbwuykMoQgHthM7ScpIyVDORHlEgD0rkzGqqY/edit

**Comment by ClementineHahn** [comment]
After update of the review checklist separating it by template section + creating one for the extra set of eyes, @SmartMouthWords and @dylanzheng94 review again. 
Last action item are:

- [ ] apply colour and styling theme of the main component template to the entirety of the doc @dy
- [ ] move the check list per section to up in order to improve their visibility. 

After those action items, ready to be used by team as a v1 . Further iterations are likely needed but good enough to be used as is.
