### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#42]
What needs to get done? 
Who needs to participate? 

____
### References: 
**Video shared by David E:**
https://www.youtube.com/watch?v=m1i_PVwtL7o  at 3:09 Gijora Dammann dives into define what needs to be versionned for a good minute.

**Comments from Francis G (captured from [this miro board](https://miro.com/app/board/o9J_l2L63J4=/)):** 
Again, as a reference in terms of WET-BOEW / GCWeb, we are using a mono-repo that follows Semantic version (as described int the Design Decision here:  https://wet-boew.github.io/wet-boew-documentation/decision/6.html ). In fact the WET-BOEW Documentation website, which is different from the main site, is the one we use to publish documents such as Design Decisions and accessibility reports, both for transparency and research purposes:  https://wet-boew.github.io/wet-boew-documentation/index-en.html . An example of an a11y assessment would be this one:  https://wet-boew.github.io/wet-boew-documentation/research/2020-37-research-a11y-sit.html 

Product cycle and versioning API were also both defined through Design decisions, respectively:  https://wet-boew.github.io/wet-boew-documentation/decision/9.html  and  https://wet-boew.github.io/wet-boew-documentation/decision/3.html . As well as browsers supported (DD-2).

FYI, I am just putting all of those references here so that we are aware of where we currently are to better understand where we want to go.

**Comment by ioanacontu** [comment]
Conversation to start in in the tech syncs this week.

**Comment by duboisp** [comment]
Here the draft on semantic versioning for the design system that I am currently working on. It's still incomplete and will require to be discussed.

----
## Semantic Versioning and public API for the Design System (Draft)

### Demystify the term

API -> A web service used to interact with or to gather information. Like Github GraphQL API, RestFull API...
API -> A public API explaining how we can interact with a product in a specific point in time. A set of rules where change would happen in the future and are risk managed by a meaningfull version number.

### What is it?

The semantic versioning is a contract with the product user, which exclude technical implementer, to quickly evaluate the impact on their work when upgrading a dependant library used by it. In other word, it allow to quickly evaluate the risk of applying changes on the published work after the completion of the dependant library update process.

- MAJOR: A Major change of the library means the user must apply change on their published work otherwise it would be broken. Upgrading to a major change often require some planing and the creation/execution of a migration plan. The meaning of a minor change are included in a major change.

- MINOR: A Minor change of the library means the user would have access to new functionality when creating new work or updating existing one. The user could probably need some training. Having new feature could require some communication, usually through different channel, the change at the users. The meaning of a patch change are included in a minor change.

- PATCH: A Patch change of the library means the user don't need to modify his work neither have new feature. But some improvement are included with the latest change. However the library still need to be implemented.

The library implementation details are out of scope by default of this versionning public API. However, for some library, depending of their purpose or their audience, might include some implementation details in their public API variant. When possible, leave those implementation details in the release note of the library along with changes description applied in the version.


#### Implemention via sub-system between the user and the library

The risk of requiring to apply a change can be direct or indirect. It is an indirect change when the dependant library is implemented through a sub-system which manage some aspect described by the public API.

A library that is implemented in a subsequent system before to reach out the user could transfer some requirement of changing the published work from the user to the implementer. So it is possible to get the major (breaking) changes fully managed and to lower the risk impact on the user. 

For example, here a major change to a library that are transformed into a patch change for the user by implementers. Let say a major version of the GCWeb library are released which require to apply some HTML markup change for the contextual feature component. For the GCWeb library, the user is the web editor that only/directly use the library to produce a web page. Let say that GCWeb library are implemented in a web content management system, like Adobe Experience Manager (AEM) and AEM have a component with a graphic user interface (GUI) to help the user to configure the contextual feature component. The HTML markup produced are not controled by the user but instead by the AEM component. Then, for the user this change in the GCWeb library don't impact them, but it will impact and require some development work by the library technical implementer to apply the HTML markup change at the component level. In that situation, the user should follow the versionning of the subsequent system. Like in the previous scenario the GCWeb change should be measured by an incrementation of the patch number of the subsequent system.

### What to version:

Formally, the component (individual feature) and the product (library) should carry their own version number. The product version to help users to be aware that changes happen in the dependency.
The component version are to help more precisly the user about what change should be applied stricly at the component level in the context of a product (library).
The third type of version are to provide guidance to stakeholder that are working on the developpement of the actual component. It is used to identify if the changes, along with how it is applied, are going to impact the version of the component. In some situation, a major/minor change can be avoided by applying the change request differently, like leveraging JavaScript to avoid a change in the HTML markup.

### 3 Type of version
* Product (Library)
	A system or a tool that directly support the design system mostly composed of a set of components.  
	For example:
	- Design tokens library
	- Guidance book
	- Reference implementation (ex: GCWeb)
	- Shape graph
	- Variant implementation of the design token library + reference implementation. For example: Adobe Experience Manager (AEM), Drupal WxT, CDS web form solution...
* Component (Feature)
	Design patterns of organic feature which are used to create an uniform and common web experience for published web content. This group represent component at different atomicity level. Sub-atomic, atomic, molecule, orgarnic and template.
	For example:
	- Alert (organic)
	- Contextual feature (organic)
	- Institutional profile (template)
	- Button (atomic)
	- Form email field composed of label, input, required marker, inline error bloc (molecule)
	- Base font (sub-atomic)
	- Color palette (sub-atomic)
* Component composition (Architecture Aspect) [[ TODO: Find a better name for this sub-division of a component and to avoid the confusion of re-using the word "component" here]]
	Pieces that put together define what a component is. A component might not include all the sub-pieces, but changes applied to individual or more pieces impact component users (Designer, Framework implementer, Web publisher, Content author). Each pieces carry it's own version number. When needed, product can be more specific on how it get measured.
	Composed of:
	- Layout (Wireframe)
	- Style (CSS)
	- Semantic (HTML)
	- Interaction pattern (Functional event listing)
	- Context of use (Guidance)
	- Configuration (Customization description)
	- Static data (Block of i18n text string)
	- Dynamic data (Shape graph)
	- Component essential dependencies (List of major versioned component)


### Component applicability scope

A website is layered and components are usually designed to apply to one layer. Only component with a defined scope should be considered to be used in a page.

Type of layer:
* Globals:
	Applicable for every pages including when defining template and providing design baseline for creating components.
	Like:
	- Base font size, color and familly
	- Default text color and background color
* Site level:
	Applicable for the majority of content web pages.
	This usually is about components that relates to common site header and common site footer. For some product, the site level could include the globals scope for brevity and simplicity.
	Like:
	- Top right search bar
	- Top menu button
	- Contact us link in the footer
* Main content level:
	Component that are applicable for main content area.
	Like:
	- Video player
	- Overlays
	- Form validation
* Template level:
	A named set of components designed to be used in a specific context. Component listed in the generic Site Level and generic Main content level could be optional. Template level might include exclusive components scoped to be at site level and main content level.
	Like:
	- Transactional page
	- Topic page
	- Institutional page
	- Splash page


### How to evaluate a version number.

The following are to help to identify if the version number need to be incremented by first evaluating the component composition.

For:
* Library: Version number is at least based on the set of supported components and specific library might includes other characteristic in their public API, like the packaging. The component title (optionally its corresponding technical name) must be a common language between all library under this design system.
* Component: Version number is based on a combination of the applicable component composition. It's not all the component composition that might be applicable for calculating the new version of a component.
* Component composition: Designed for component designed, each composition element have their own version number. A specific library, like the reference implementation GCWeb, might add some specificity on how those component composition version are evaluated and mitigated in the product (library).


### Component composition:

* Layout (ex. Wireframe): 

	Defined by how atom and molécule pieces are organized among others within a component. Multiple layout can be supported for the same component. Removing or adding pieces create more sub-layout variant.

	- Major layout change: When a defined sub-layout is removed or reorganized. Merging two sub-layout is considered reorganized.
	- Minor layout change: When a new layout variant is added.
	- Patch layout change: N/A

	Library variant:
		* Reference implementation (GCWeb)
			- Major: When a defined sub-layout is removed or a reorganization that require web author/web developer to update their existing pages.
			- Minor: When a new layout variant is added.
			- Patch: A reorganization that can be applied without changing anything exception of implementing (installing) the updated library. That means the changes is fully managed by the library.

	Example of metrics:
		* Wireframe
		* Rendered HTML that leverage a CSS positioning mechanism (ex. grid system)

* Style (ex. CSS):

	- Major style change: Significative changes that change the meaning of the component or/and directly imply a major change for another component composition (like Layout, Semantic...).
	- Minor style change: The addition of a new styles in order to visually enhance the component based on addition of a new configuration.
	- Patch style change: Update to an existing style or an addtion that don't imply a new configuration or an addition that enhance the component with no change in meaning of hte component.

	Library variant:
		* Reference implementation (GCWeb)
			- Major: A removal or a change of CSS class name that provide meaning and require a web author/web developer intervention to update the published content. A style that impact the published content to be reviewed, re-architured, re-organised or re-published to avoid breaking change in the communication. The removal of a styled configuration that is repurposed to a new component or guidance that are updated in a matter to deprecate the use of such configuration.
				For example, increasing the font size from 16px to 20px considerably impact campaign page that are tightly designed to use all the available space without impacting the layout of the promotional content.
			- Minor: The addition of a new style or a new class name that support a new configuration.
			- Patch: Change that can be applied without changing anything exception of implementing (installing) the updated library. That means the changes is fully managed by the library.
				For example, the visual change for the alert component where the alert in a colored box (Bootstrap 3) is now change to be a large left colored border.

	Example of metrics:
		* Set of CSS/SASS rules
		* Textual description of the style itemized 

* Semantic (ex. HTML):

	- Major change:
	- Minor change:
	- Patch change:

	Library variant:
		* Reference implementaiton (GCWeb)
			- Major:
			- Minor:
			- Patch:
	Example of metrics
		* HTML markup ordered and excluding generic element

* Interaction pattern (ex. Functional event listing):

	- Major change:
	- Minor change:
	- Patch change:

	Library variant:
		* Reference implementaiton (GCWeb)
			- Major:
			- Minor:
			- Patch:
	Example of metrics
		* Functional event listing

* Context of use (ex. Guidance):

	- Major change:
	- Minor change:
	- Patch change:

	Library variant:
		* Reference implementaiton (GCWeb)
			- Major:
			- Minor:
			- Patch:
	Example of metrics
		* Guidance

* Configuration (ex. Customization description):

	- Major change:
	- Minor change:
	- Patch change:

	Library variant:
		* Reference implementaiton (GCWeb)
			- Major:
			- Minor:
			- Patch:
	Example of metrics
		* Customization description

* Static data (ex. i18n text string):

	- Major change:
	- Minor change:
	- Patch change:

	Library variant:
		* Reference implementaiton (GCWeb)
			- Major:
			- Minor:
			- Patch:
	Example of metrics
		* i18n text string
		* unlocalized key identifying a i18n text string

* Dynamic data (ex. Shape graph):

	- Major change:
	- Minor change:
	- Patch change:

	Library variant:
		* Reference implementaiton (GCWeb)
			- Major:
			- Minor:
			- Patch:
	Example of metrics
		* Shape graph

* Component essential dependencies (ex. List of major versioned component):

	- Major change:
	- Minor change:
	- Patch change:

	Library variant:
		* Reference implementaiton (GCWeb)
			- Major:
			- Minor:
			- Patch:
	Example of metrics
		* List of major versioned component


###
Shape Graph

(todo)
----

**Comment by ioanacontu** [comment]
To be presented at the next tech sync and with the product team.

**Comment by duboisp** [comment]
I updated my draft published in my [previous comment](https://github.com/cds-snc/design-gc-conception/issues/42#issuecomment-920005362)

**Comment by duboisp** [comment]
Tel que commenté par @mcman12 ce matin. Il avait suggéré d'inclure le risque d'implémentation d'un produit. Il n'est pas nécessaire d'avoir cette discussion maintenant.

J'ai intentionnellement exclus l'implémentation dans l'ébauche de API publique car, dans notre context au gouvernement, l'implémentation du produit est rarement fait par l'utilisateur du produit pour en produire du contenu.

Au moment venu, il va falloir déterminer la périodicité de la release du Design system. Je propose que le Design system soit un ensemble de produits associés à une version ainsi qu'un descriptif du risque associé à son implémentation. En même temps, ceci permettrait de mettre en place un processus de synchronization entre les divers produits et de s'assurer que les components soit développé ou mis à jour à temps. On pourrait avoir un numéro de version pour le Design System un peu comme Ubuntu "YYYY-MM".

**Comment by ioanacontu** [comment]
Reviewing the public API with Francis. Preparing a presentation for how we will be measuring versioning/changes. 
Review from the Guidance Pod required as a follow-up. How we track changes in the guidance/code.

**Comment by ioanacontu** [comment]
Pierre, David E and Francis meeting this afternoon - discussion on the governance protocol/public API.

**Comment by duboisp** [comment]
Summary of Oct 4 tech sync: 

_(still an open discussion)_

* Mention that we need to define and have a common understanding of what is a "component".
* Looking for a better name for "Component composition" which is used to name the group of a set of breakdown component element. Some proposition was: elements, layers, attributes, properties, sub-components.
* Sam will look to visualize the versioning (major vs minor vs minor).
* It was mention this document don't necessary need to be fully finalize at this point of time considering that we are early with the development of  new solution/product issue from the GC Design System, like the design token. But it was mention this documents, at least early draft, is needed to ensure interoperability between solution/product.

**Comment by mcman12** [comment]
putting back in the backlog. Focusing the work on the proof of concept.
We will revisit this work in the near future.
