### ISSUE TITLE
Naming convention methodology [Propose a] 

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#55]

**Comment by ioanacontu** [comment]
Started to work on a repo. Mario created an official repo for design tokens. Connecting with Josh to look at different naming schemes and conventions.

**Comment by ioanacontu** [comment]
David E pushed to the repo the experiment done yesterday. Will review with Josh.

**Comment by ioanacontu** [comment]
To be discussed at this week's tech sync.

**Comment by ioanacontu** [comment]
This was discussed on Monday at the tech sync. Got feedback from Pierre. David E to provide the conclusions of the discussion.

**Comment by delisma** [comment]
Effective token names improve and sustain a team’s shared understanding of visual style through design, code, and other interdisciplinary handoffs. Terms matter. As we make things, we must be able to browse and search tools to quickly recognize and recall the purposeful decisions we’ve made. Not just in code and documentation, but in design tools too. As tokens become more sophisticated, naming patterns matter.

![image.png](https://images.zenhubusercontent.com/60f701f751d0f3aa4eca91ad/4c788e29-66ac-49fd-b389-522ef2c03805)
So far we agree that tokens should be split in 2 main categories (functions):
- **alias** (raws, primitives, bases, particles, generics) tokens
   - Should be used by other tokens that inform a broader design decision. 
   - Hold raw values like colour code, font names, size and space hierarchy scale, etc.
   - Should **not be used directly by design system users**. 
   - The aliases should follow a simple CTI format, which stands for _category_, _type,_ _item_ (even though we may drop the item part for these)
- **decision** tokens.
   - These tokens should always refer to an alias and not to a raw value (see image above)
   - Should be used by design system users to implement systems or to create new components and patterns.
   - Should follow a more complex ICT format, where the _item_ part becomes an _object_ and can be divided in 3 labels (group, component, element) and the _category_ (color, font, space, size, elevation, breakpoints, touch, time) follows the _item_ to inform what decision we've made for a particular component. 

As well, we're looking into namespacing the tokens following this schema `[system]-[theme]-[platform]`. 

The preferred system prefix would be `gc-` instead of `gcds-`.
![image.png](https://images.zenhubusercontent.com/60f701f751d0f3aa4eca91ad/acdbbc36-d52a-4b7e-983f-b83ea642ead7)

The namespace for **alias tokens** would be `gc-[theme]-brand-` to inform that nobody can change their raw values unless it goes through the DS system team and some kind of approval process. 

The other tokens could be namespaced `gc-[theme]-[platform]-` if specificity is required (except for shared tokens).
