### ISSUE TITLE
Governance model - research and recommendation

### ISSUE THREAD

**Issue by brockhigg10** [cds-snc/design-gc-conception#632]

**Comment by brockhigg10** [comment]
Establishing governance models for:

- Design decisions
- Contribution decisions

**Comment by brockhigg10** [comment]
https://zeroheight.com/help/guides/design-system-governance-models-and-which-is-right-for-your-organization/

https://www.youtube.com/watch?v=ejhk8tDO5fU&feature=youtu.be

Solitary team modelNew DS might not get a lot of love at first while you’re building it. It might just be one person’s baby, one designer or one dev who’s super passionate… what we find is rarely is that person able to sustain the design system with singular oversight… if all goes well, you very quickly get inundated with questions about using, updating, maintaining… it’s not a sustainable model for one person to have oversight of a DS

Centralized team modelBF: One model that can work well is a centralized team model, so you have a dedicated product team that is responsible for making, grooming maintaining and evolving the system. That kind of team structure has the sort of systems view, all of those people are thinking about the entirety …. Risk of that model is it can lose that on-the-ground perspective

Federated team modelYou don’t have a centralized team doing all the production work, rather representatives that work on different products scattered across the org. And all of those people are representatives that are sort of maintaining the systemRisk with this is that product roadmaps always take priority. So these ppl’s attention is split with serving real product needs and the system-lens or bird’s eye perspective is lost.

The cyclical model or Salesforce model (Jina put this in place at Salesforce)Combination of centralized team and federated members. Centralized team doing a lot of work but also federated members that are able to feed that in-the-weeds perspective to the DS. Diverse model. You’ve got a bird’s-eye view, on-the-ground perspectives… Maybe you have execs on the team and you have makers doing the work as well. This model scales well.Potentially you could have an advisory board of folks who aren’t even in your org! —This is what Etsy did, they struck a committee that meets once a month with reps from different areas that get together. There’s a committee leader but they also bring in different owners from different products, so you have different products represented. Web, iOS, Android, email properties all have a seat at the table. But also brought in subject matter experts, like a11y, performance, responsive design…

**Comment by CelesteCote** [comment]
Recommending we adopt the Salesforce combined model of a centralized team with federated members.

A centralized team of contributing partners can come together gradually one by one. These could conceivably be the major service provider departments — Service Canada (already in process), DTO/PP (sprint zero next week), CRA and IRCC (perhaps later? maybe a rep or two from each can embed in this team further down the line?)

Ideally we could build a community of users that could make up the 'federated membership' portion that would again be established gradually as we expand our user base. Users will perhaps have use cases for new components and we'll want to have:

1. criteria for considering new components or patterns
2. a review process in place
3. an operational understanding that things take time — propose that instead of "if you need something we don't have, go ahead and build it", we extend that to "and please let us know, we'll put it in the back log and circle back with you when we're ready" so that we can leverage work and research and talent across the GC and also facilitate cohesion across products.
