### ISSUE TITLE
Review and translate English component posters

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#672]

**Comment by ClementineHahn** [comment]
Can we have a checklist to follow progression of components translated-reviewed please @dylanzheng94 ? Thank you

**Comment by SmartMouthWords** [comment]
- Reviewed website component names, other names, and definitions across components. Added these to a [spreadsheet ](https://docs.google.com/spreadsheets/d/1B57hJZHwxsleHVweisIkJOCKLNenJTCtZjx84KwyvoI/edit#gid=0)and flagged a number of content bugs / inconsistencies.
-

**Comment by SmartMouthWords** [comment]
Reviewed Welcome, get started, and styles pages, as well as menu for posters/components. 

Some incomplete content/strings and some needs updating. Found some additional general design issues.   
	
**Cover page**	
- We're using a Canada flag. Does this meet FIP? Should we consider replacing with the signature?
- Do we need to cover page to match our branding colours?
- Is there a way to automate the last updated date or can we build that into the update process? Right now it says November 2023

**Getting Started**	
- The getting started page contains incomplete content. Do we want to: a) remove it for now? b) update it with content from the video Dylan made?

Styles page	
- The heading for font weights is missing content beneath it. Is it important to have this section?
- A few of the frames need names
- How do we want to mention the relationship between the styles and the gcds-tokens on this page?
- Noting this page differs visually from the component pages

Figma library menu
- The grid page appears to be out of place. is this intentional?
- should the components not published on the website be separated out? Alert, banner, date input, mobile navigation, phase banner 
- The following are already separate:  navigation tabs, table, margin. Do we want to treat these all the same? 
- Should archived work be moved out and into the file Ravina started?

**Comment by SmartMouthWords** [comment]
- Updated component posters and content
- @nmakuch added anatomy descriptions for all components and prepping posters for translation once I flag as ready

@EliseKa In the[ internal assets branch](https://www.figma.com/file/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?type=design&node-id=1%3A4763&mode=design&t=o9iu4erpXPOdoMEh-1) of the library: Pages for component posters that are ready for translation are in the top section "Posters ready for translation" and have a green checkmark.

**Comment by SmartMouthWords** [comment]
@nmakuch is pulling French versions into new library to create French posters and files

**Comment by mcman12** [comment]
Nicholas ready to do the review after we ensure english and french match

**Comment by adorayi** [comment]
@nmakuch @SmartMouthWords is this now with Nicholas for bilingual review?

**Comment by SmartMouthWords** [comment]
Ready for @nchoquet and @EliseKa review. 
French library: https://www.figma.com/file/o4SguSZdar2CCFzSkWNrmB/Syst%C3%A8me-de-design-GC?type=design&node-id=114%3A1347&mode=design&t=IxGDJiBY3nzbLv9y-1
English library:  https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?type=design&node-id=4%3A1006&mode=design&t=UYIf140yr9f5l2FE-1
Internal assets file: https://www.figma.com/file/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?type=design&node-id=1%3A3308&mode=design&t=V6icSNIqmlfOeFrT-1

**Comment by SmartMouthWords** [comment]
@realdylanzheng @nmakuch @RavinaSamaroo Please flag if there's been any recent update to the English content that's not yet reflected in the French.

**Comment by adorayi** [comment]
@adorayi Follow up with @nchoquet and @EliseKa
