### ISSUE TITLE
Design: Stepper v2

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#700]
**Summary:** Design of the stepper component. 
Design on component branch and push to main Figma file when approved.

**Acceptance Criteria:**

- [ ] Component Kickoff
- [ ] Sync with Dev and Design
- [ ] Research and consulting other design libraries
- [ ] WCAG Goal can be completed using a screen reader.
- [ ] WCAG Visual elements observe color contrast requirements.
- [ ] WCAG Manual accessibility testing meets WCAG 2.1 AA requirements.
- [ ] Provides equal service in French and English.
- [ ] Sync with Dev and Design
- [ ] Comparison with official policy, documented reasons for deviation if any
- [ ] Design review
- [ ] [Policy review](https://www.figma.com/file/p0eiLxdme1g93sIuggjipR/Colour-%26-typography-differences-GCDS-vs.-Canada.ca?type=design&node-id=0-1&t=kkavFCQ74dMoZw6V-0)
- [ ] Design - Different screen sizes 
- [ ] Design - Short content / long content (text overflow etc.)
- [ ] Design - Error state (if applicable)
- [ ] Design - Empty state (if applicable)
- [ ] Component anatomy
- [ ] Write draft of design guidance
- [ ] Handoff from draft dev guidance to documentation author/lead
- [x] Update Figma version

**Comment by ClementineHahn** [comment]
Work in Figma was actually done to apply changes such as : stepper can now be used in a H2 instead of a H1. Small task in all the places to be changed and released so complex task form a review, collab point of view. 
Left to be done 

- [ ] update website guidance 
- [ ] update web packages to match update & release
- [ ] Create new anatomy
- [ ] Create new alt text
- [ ] Create preview 
- [ ] translate new website guidance
- [ ] publish new website guidance

**Comment by adorayi** [comment]
Split into different tickets, all resolved.
