### ISSUE TITLE
Button review

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#958]
https://test.canada.ca/gcds-gcweb/en/components/buttons

**Comment by delisma** [comment]
- How can we keep the Supertask button [because some research show the success of it](https://docs.google.com/document/d/1BfqYgcctsE-8IxATOmvirHksAd0f_2INs0EyuzYEG3o/edit#heading=h.9fzn9rvtxnbu)
- We can update the look of the Supertask to match the modern look of GCDS
- Keep the Sign In button because CRA no visual updates
- Other button styles are straight from Bootstrap 3 w no overrides
- Canada.ca buttons should update to match the GCDS look
- TODO: Scan of Canada.ca to see which buttons are widely use at the moment
  - Warning, info, success?
  - Sizes?
- ~~We need a better guidance for buttons and links to avoid confusion about use cases~~

**Comment by delisma** [comment]
- The sign in button is a <a> link styled as button: Suggested to be treated as a slot of the header in GCDS
- Supertask button can be added. Seems like more discussions could land to a decision.
- The sizing of buttons could be cleaned up in GCWeb (lg and xs size) so we don't need to work on parity on GCDS.
